import json

CONFIG_MODEL_KEY = "Model"
CONFIG_MODEL_TYPE_SUBKEY = "Type"
CONFIG_MODEL_CKPTSAVEPATH_SUBKEY = "PathCKPT"
CONFIG_MODEL_CKPTFILENAME_SUBKEY = "NameCKPT"
CONFIG_TRAINING_KEY = "Training"
CONFIG_TRAINING_NOISE_SUBKEY = "Noise"
CONFIG_TRAINING_NOISE_COUNT_SUBSUBKEY = "Count"
CONFIG_TRAINING_NOISE_DIMENSIONS_SUBSUBKEY = "Dimensions"
CONFIG_TRAINING_NOISE_MEAN_SUBSUBKEY = "Mean"
CONFIG_TRAINING_NOISE_STDDEV_SUBSUBKEY = "STDDEV"
CONFIG_TRAINING_SAMPLES_SUBKEY = "Samples"
CONFIG_TRAINING_SAMPLES_COUNT_SUBSUBKEY = "Count"
CONFIG_TRAINING_SAMPLES_DIMENSIONS_SUBSUBKEY = "Dimensions"
CONFIG_TRAINING_SAMPLES_TYPE_SUBSUBKEY = "Type"
CONFIG_TRAINING_EPOCHS_SUBKEY = "Epochs"
CONFIG_TRAINING_EPOCHS_MAIN_SUBSUBKEY = "Main"
CONFIG_TRAINING_EPOCHS_GEN_SUBSUBKEY = "Gen"
CONFIG_TRAINING_EPOCHS_DISC_SUBSUBKEY = "Disc"
CONFIG_TRAINING_BATCHSIZE_SUBKEY = "BatchSize"
CONFIG_TRAINING_BATCHSIZE_GEN_SUBSUBKEY = "Gen"
CONFIG_TRAINING_BATCHSIZE_DISC_SUBSUBKEY = "Disc"
CONFIG_TRAINING_DEBUG_KEY = "Debug"
CONFIG_TRAINING_DEBUG_INTERVALS_KEY = "Intervals"
CONFIG_TRAINING_DEBUG_INTERVALS_PRINTLOSSGEN_KEY = "PrintLossGen"
CONFIG_TRAINING_DEBUG_INTERVALS_PRINTLOSSDISC_KEY = "PrintLossDisc"
CONFIG_TRAINING_DEBUG_INTERVALS_SAVECKPT_KEY = "SaveCKPT"

class ConfigLoader:
	def __init__(self, file_json):
		f = open(file_json)
		self._config = json.load(f)
		self.load_configs()
		f.close()
		
	def load_configs(self):
		self.model_type = self._config[CONFIG_MODEL_KEY][CONFIG_MODEL_TYPE_SUBKEY]
		self.ckpt_save_path = self._config[CONFIG_MODEL_KEY][CONFIG_MODEL_CKPTSAVEPATH_SUBKEY]
		self.ckpt_file_name = self._config[CONFIG_MODEL_KEY][CONFIG_MODEL_CKPTFILENAME_SUBKEY]
		self.noise_count = self._config[CONFIG_TRAINING_KEY][CONFIG_TRAINING_NOISE_SUBKEY][CONFIG_TRAINING_NOISE_COUNT_SUBSUBKEY]
		self.noise_dims = self._config[CONFIG_TRAINING_KEY][CONFIG_TRAINING_NOISE_SUBKEY][CONFIG_TRAINING_NOISE_DIMENSIONS_SUBSUBKEY]
		self.noise_mean = self._config[CONFIG_TRAINING_KEY][CONFIG_TRAINING_NOISE_SUBKEY][CONFIG_TRAINING_NOISE_MEAN_SUBSUBKEY]
		self.noise_stddev =  self._config[CONFIG_TRAINING_KEY][CONFIG_TRAINING_NOISE_SUBKEY][CONFIG_TRAINING_NOISE_STDDEV_SUBSUBKEY]
		self.samples_count = self._config[CONFIG_TRAINING_KEY][CONFIG_TRAINING_SAMPLES_SUBKEY][CONFIG_TRAINING_NOISE_COUNT_SUBSUBKEY]
		self.samples_dims = self._config[CONFIG_TRAINING_KEY][CONFIG_TRAINING_SAMPLES_SUBKEY][CONFIG_TRAINING_SAMPLES_DIMENSIONS_SUBSUBKEY]
		self.samples_type = self._config[CONFIG_TRAINING_KEY][CONFIG_TRAINING_SAMPLES_SUBKEY][CONFIG_TRAINING_SAMPLES_TYPE_SUBSUBKEY]
		self.num_epochs_main = self._config[CONFIG_TRAINING_KEY][CONFIG_TRAINING_EPOCHS_SUBKEY][CONFIG_TRAINING_EPOCHS_MAIN_SUBSUBKEY]
		self.num_epochs_gen = self._config[CONFIG_TRAINING_KEY][CONFIG_TRAINING_EPOCHS_SUBKEY][CONFIG_TRAINING_EPOCHS_GEN_SUBSUBKEY]
		self.num_epochs_disc = self._config[CONFIG_TRAINING_KEY][CONFIG_TRAINING_EPOCHS_SUBKEY][CONFIG_TRAINING_EPOCHS_DISC_SUBSUBKEY]
		self.batch_size_gen = self._config[CONFIG_TRAINING_KEY][CONFIG_TRAINING_BATCHSIZE_SUBKEY][CONFIG_TRAINING_BATCHSIZE_GEN_SUBSUBKEY]
		self.batch_size_disc = self._config[CONFIG_TRAINING_KEY][CONFIG_TRAINING_BATCHSIZE_SUBKEY][CONFIG_TRAINING_BATCHSIZE_DISC_SUBSUBKEY]
		self.print_interval_loss_gen = self._config[CONFIG_TRAINING_DEBUG_KEY][CONFIG_TRAINING_DEBUG_INTERVALS_KEY][CONFIG_TRAINING_DEBUG_INTERVALS_PRINTLOSSGEN_KEY]
		self.print_interval_loss_disc = self._config[CONFIG_TRAINING_DEBUG_KEY][CONFIG_TRAINING_DEBUG_INTERVALS_KEY][CONFIG_TRAINING_DEBUG_INTERVALS_PRINTLOSSDISC_KEY]
		self.save_interval_ckpt = self._config[CONFIG_TRAINING_DEBUG_KEY][CONFIG_TRAINING_DEBUG_INTERVALS_KEY][CONFIG_TRAINING_DEBUG_INTERVALS_SAVECKPT_KEY]
		

